id: B
seed: 3698
model:
    name: MLPClassifier
    args:
        input_dim: 2
        hidden_dims: [3]
        output_dim: 1
        activation: relu
optimizer:
    name: SGD
    args:
        lr: 1.0
loss:
    name: MSELoss
    args:
metric:
    - name: Accuracy
      args:
dataset:
    train:
        name: HWDataset
        args:
            X_npy_path: data/X_train.npy
            y_npy_path: data/y_train.npy
        loader:
            name: DataLoader
            args:
                batch_size: 1000
                shuffle: True
                pin_memory: True
    val:
        name: HWDataset
        args:
            X_npy_path: data/X_val.npy
            y_npy_path: data/y_val.npy
        loader:
            name: DataLoader
            args:
                batch_size: 20000
                pin_memory: True
trainer:
    nepochs: 500
    val_step: 1
    log_step: 1
    log_dir: runs
